### ISSUE TITLE
FacebookBlock fails to configure

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/facebook#50]
```
[2018-08-02T20:13:54.797500Z] NIO [ERROR] [an arbitrary service.8cc1aa91-b9c3-448c-944d-949c80cd2955] Failed to con
figure
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nio\util\runner.py", line 79, in do_c
onfigure
    self.configure(context)
  File "C:\Users\Tom\nio\projects\block-audit\blocks\facebook\facebook_block.py", line 62, in configure
    super().configure(context)
  File "C:\Users\Tom\nio\projects\block-audit\blocks\facebook\rest_polling\rest_block.py", line 64, in configure
    self._authenticate()
  File "C:\Users\Tom\nio\projects\block-audit\blocks\facebook\facebook_block.py", line 76, in _authenticate
    self._access_token = self._request_access_token()
  File "C:\Users\Tom\nio\projects\block-audit\blocks\facebook\facebook_block.py", line 136, in _request_access_toke
n
    token = resp.text.split('access_token=')[1]
IndexError: list index out of range
```

Printing `resp.text` seems to show that the API response changed at some point and we are now getting a JSON object in the response, instead of what I assume used to be plain-text string:
`{"access_token":"<my-token>","token_type":"bearer"}`

**Comment by tyoungNIO** [comment]
This also applies to FacebookFeed
